// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF4oYmsIYQnIeV__np3C4BaTLIBlfAt6I',
    appId: '1:520893413502:web:83f860fc4da9468ec7002f',
    messagingSenderId: '520893413502',
    projectId: 'notification-receiver-8064d',
    authDomain: 'notification-receiver-8064d.firebaseapp.com',
    storageBucket: 'notification-receiver-8064d.firebasestorage.app',
    measurementId: 'G-6MSGCS3HQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlJkRM9SrwUo9Q-WQq6vkXqFhAVRNqoNQ',
    appId: '1:520893413502:android:1e8603136cce8a72c7002f',
    messagingSenderId: '520893413502',
    projectId: 'notification-receiver-8064d',
    storageBucket: 'notification-receiver-8064d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm-H805WWotvvDN1IhSBZfUeHd-antQOg',
    appId: '1:520893413502:ios:5cbe74d462283f56c7002f',
    messagingSenderId: '520893413502',
    projectId: 'notification-receiver-8064d',
    storageBucket: 'notification-receiver-8064d.firebasestorage.app',
    iosBundleId: 'com.example.receiverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm-H805WWotvvDN1IhSBZfUeHd-antQOg',
    appId: '1:520893413502:ios:5cbe74d462283f56c7002f',
    messagingSenderId: '520893413502',
    projectId: 'notification-receiver-8064d',
    storageBucket: 'notification-receiver-8064d.firebasestorage.app',
    iosBundleId: 'com.example.receiverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF4oYmsIYQnIeV__np3C4BaTLIBlfAt6I',
    appId: '1:520893413502:web:348248f4b8701c9ac7002f',
    messagingSenderId: '520893413502',
    projectId: 'notification-receiver-8064d',
    authDomain: 'notification-receiver-8064d.firebaseapp.com',
    storageBucket: 'notification-receiver-8064d.firebasestorage.app',
    measurementId: 'G-8JSC498DDB',
  );
}
